# Generated by Django 2.2.7 on 2019-11-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191120_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to=''),
        ),
    ]
